version: '3'

services:
  api:
    container_name: api
    build:
      context: ./node
    environment:
      - DB_NAME=desafio
      - DB_PASSWORD=qwe123
      - DB_USER=root
      - DB_HOST=database
      - DB_PORT=3306
    depends_on:
      - database
    volumes:
      - ./node:/app
    networks:
      - desafio
  
  database:
    container_name: database
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_ROOT_PASSWORD=qwe123
      - MYSQL_DATABASE=desafio
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - desafio
    
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - desafio
    depends_on:
      - api

volumes:
  db_data:

networks:
  desafio:
    driver: bridge